### ISSUE TITLE
Setting absTime doesn't work

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-beacon-v2#137]
in chart ui or in query wizard (maybe even in keen query??)

**Comment by andygout** [comment]
I can create graphs that use absolute time which seem to display accurate data (CTR on a component that was down over the weekend reads zero results for that specific component) but having same probs with chart UI and query wizard.

**Comment by wheresrhys** [comment]
cheers for the info

**Comment by wheresrhys** [comment]
hopefully fixed now. Reopen if not
