### ISSUE TITLE
Beacon Query WIzard not updating results

### ISSUE THREAD

**Issue by ChristianValle** [Financial-Times/next-beacon-v2#143]
when changing paramaters in the query, the print table output is not updated 

a) original query
cta:click->count(device.spoorId)->filter(context.domPath~logo-link)->group(context.domPath)->print(Table)->relTime(previous_14_days)
results 34/161

b) change query 
cta:click->count(device.spoorId)->filter(context.domPath~logo-link)->group(context.domPath)->print(Table)->relTime(this_1_days)

results 34/161 (SAME)

**Comment by adambraimbridge** [comment]
The query wizard is still a work in progress. 

But in the meantime please try moving the ->print(Table) to the very end; e.g:

`cta:click->count(device.spoorId)->filter(context.domPath~logo-link)->group(context.domPath)->relTime(previous_14_days)->print(Table)`

`cta:click->count(device.spoorId)->filter(context.domPath~logo-link)->group(context.domPath)->relTime(this_1_days)->print(Table)`

**Comment by wheresrhys** [comment]
ah - good spot Adam.
