### ISSUE TITLE
Split out keen proxy

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-beacon-v2#152]
Because
- It slows down loading of beacon pages
- S3O is not required for it, so it's an overhead
- The email team may like to use our cached proxy too

Let's take the keen proxy out into its own app and add some neat features
- handle POST?
- allow for a ttl header to manually set the cache headers

We can also start slow polling this proxy to prehydrate the cache and avoid hitting our keen concurrency limits

**Comment by wheresrhys** [comment]
Would this even need a backend? Can we just handle CORS and and Cache-control in VCL and point straight at api.keen.io?

**Comment by matthew-andrews** [comment]
api.keen.io serves * CORS headers so you might be able to point dreckly to that from the front end.

**Comment by wheresrhys** [comment]
This is so we can add a caching layer for performance. We already do this,
but want to split out so email team can share in the performance boost and
to avoid the keen proxy impacting response times for html pages served by
beacon (which it seems to be doing)

On Saturday, 19 March 2016, Matt Andrews <notifications@github.com> wrote:

> api.keen.io serves * CORS headers so you might be able to point dreckly
> to that from the front end.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-beacon-v2/issues/152#issuecomment-198706005>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by matthew-andrews** [comment]
makes sense^^

**Comment by wheresrhys** [comment]
need to consider using shielding
