### ISSUE TITLE
Pie charts: Render labels on the right hand side

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-beacon-v2#25]
![image](https://cloud.githubusercontent.com/assets/224547/12727338/8740e70e-c914-11e5-8486-5a54ca999d0c.png)
http://ft-next-beacon-v2.herokuapp.com/chart/anonymous/referrers

**Comment by wheresrhys** [comment]
done.

**Comment by wheresrhys** [comment]
I'm thinking for line charts with more than about 5 lines we could suppress the google charts legend and make our own widget - we have full information about the text and allocation of colours so it's totally doable
