### ISSUE TITLE
Slots data is being included in page:view context

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-beacon-v2#522]
See: https://beacon.ft.com/data/extract/page:view ... There’s a few `o-ads-slot` fields being sent to spoor.

![image](https://cloud.githubusercontent.com/assets/224547/20394583/f41f1ac4-acd7-11e6-908c-dd7cbf053c4b.png)

Todo: 
 - [ ] Find out what's adding the slots object to the oTracking page:view context (or indeed, whether or not this is what's actually happening) 
 - [ ] Either remove the code or move it to a more appropriate event collection (other than page:view)
 - [ ] Delete the `slots` noise from keen.io

* Query showing page view events that have a `context.slots.o-ads-slot-1061.center` property:
https://beacon.ft.com/data/explorer?query%5Bevent_collection%5D=page%3Aview&query%5Banalysis_type%5D=count&query%5Binterval%5D=daily&query%5Btimezone%5D=UTC&query%5Bfilters%5D%5B0%5D%5Bproperty_name%5D=context.slots.o-ads-slot-1061.center&query%5Bfilters%5D%5B0%5D%5Boperator%5D=exists&query%5Bfilters%5D%5B0%5D%5Bproperty_value%5D=true&query%5Btimeframe%5D=this_120_days

* https://github.com/Financial-Times/o-ads/blob/master/src/js/slot.js#L294g  <— that’s where the o-ads-slot is being named

* https://github.com/Financial-Times/n-ui/blob/master/ads/js/metrics.js#L11  <— this is the only ads-related o-tracking event in o-ads (?)

**Comment by adambraimbridge** [comment]
https://docs.google.com/spreadsheets/d/1pl9CwR73v6uRTRyqiYKt1dCrQPkqJyt4B6cNHkdj7DM/edit#gid=0

**Comment by commuterjoy** [comment]
@andygnewman any chance we could have one `ad-slot` event with a property of `slot.id` or similar?

the keen.io docs expressly advise against naming collections after variables.

**Comment by adambraimbridge** [comment]
I discussed this with @andygnewman. It turns out that the fact that ads slots are prevalent is a red herring. 

Ads are adding dom elements with `slot` attributes as are other apps; but _something else_ is adding them to the event context. At least, that seems to be the case. I can't find the code that's responsible.

**Comment by adambraimbridge** [comment]
I've added a filter to spoor-consumer that deletes all "slot*" properties from events. 

However @tom-parker and I still want to spend time investigating the mysterious source of these event properties.

**Comment by adambraimbridge** [comment]
I liaised with Ricky from Keen.io, who worked with their team to delete all "slot" properties from our event collections.
