### ISSUE TITLE
Dompath data in keen is not ideal

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-beacon-v2#59]
![image](https://cloud.githubusercontent.com/assets/224547/13150436/af730b0c-d65d-11e5-905a-abe5edb2c539.png)

http://ft-next-beacon-v2.herokuapp.com/data/explorer?query%5Bevent_collection%5D=page%3Ascrolldepth&query%5Banalysis_type%5D=count&query%5Bgroup_by%5D=context.domPath&query%5Btimezone%5D=UTC&query%5Btimeframe%5D=this_14_days

My guess is that the results are all "undefined" because the domPath value for each event is stored as an array rather than as a string.

https://github.com/Financial-Times/n-instrumentation/blob/master/src/utils/getDomPath.js

This is the same for oldkeen and newkeen.

**Comment by wheresrhys** [comment]
as discussed, this is due to the scroll events on the home page sending an array rather than a string, so not a bug with beacon/kq per se
